silly_name1 = input("Enter a Silly Name: ")
unrealistic_profession = input("Enter an Unrealistic Profession: ")
country = input("Enter a Country: ")
silly_name2 = input("Enter another Silly Name: ")
color1 = input("Enter a Color: ")
adjective1 = input("Enter an Adjective: ")
adverb1 = input("Enter an Adverb: ")
silly_name3 = input("Enter another Silly Name: ")
silly_name4 = input("Enter another Silly Name: ")
facial_feature = input("Enter a Facial Feature: ")
us_city = input("Enter a US City: ")
silly_name5 = input("Enter one more Silly Name: ")
verb = input("Enter a verb: ")
noun1 = input("Enter a noun: ")
badass_actor = input("Enter a Formerly Badass Actor Now Selling Out: ")
noun2 = input("Enter one more Noun:")

print(" ")
print("_______________________________________________________________________________________________________________________")
print(" ")
print("Meet our hero " + silly_name1 + ", a super intelligent " + unrealistic_profession + ". A")
print("run-in with the " + country + " military leads him to create his alter-ego")
print(silly_name2 + ", a " + color1 + " " + adjective1 + " giant capable of great")
print("destruction. He " + adverb1 + " battles the military with his girlfriend")
print(silly_name3 + ". " + "Eventually it is discovered that our hero's long time")
print("colleague " + silly_name4 + ", distinguished by his " + facial_feature + " is trying")
print("turn " + silly_name2 + " into a weapon, leading to climactic (if pointless)")
print("battle in downtown " + us_city + " with an evil version of the")
print("same giant alter-ego called " + silly_name5 + ". Eventually the enemy is")
print("subdued by " + verb + "ing him with a " + noun1 + ". In the final reel,")
print(badass_actor + " appears to propose joining him in a " + noun2 + ".")